# Generated by Django 4.2 on 2023-04-13 15:49

from django.db import migrations

input = [
    ("Bahrain International Circuit", "Sahkir", "Bahrain"),
    ("Jeddah Corniche Circuit", "Jeddah", "Saudi Arabia"),
    ("Albert Park Circuit", "Melbourne", "Australia"),
    ("Baku City Circuit", "Baku", "Azerbaijan"),
    ("Miami International Autodrome", "Miami", "USA"),
    ("Autosromo Enzo e Dino Ferrari", "Imola", "Italy"),
    ("Circuit de Monaco", "Monte Carlo", "Monaco"),
    ("Circuit de Barcelona-Catalunya", "Catalunya", "Spain"),
    ("Circuit Gilles-Villeneuve", "Montreal", "Canada"),
    ("Red Bull Ring", "Spielburg", "Austria"),
    ("Silverstone Circuit", "Silverstone", "Great Britain"),
    ("Hungaroring", "Budapest", "Hungary"),
    ("Circuit de Spa-Francorchamps", "Spa-Francorchamps", "Belgium"),
    ("Circuit Zandvoort", "Zandvoort", "Netherlands"),
    ("Autodromo Nazionale Monza", "Monza", "Italy"),
    ("Marina Bay Street Circuit", "Marina Bay", "Singapore"),
    ("Suzuka International Racingf Course", "Suzuka", "Japan"),
    ("Lusail International Circuit", "Lusail", "Qatar"),
    ("Circuit of The Americas", "Austin", "USA"),
    ("Autodromo Hermanos Rodriguez", "Mexico City", "Mexico"),
    ("Autodromo Jose Carlos Pace", "Sao Paulo", "Brazil"),
    ("Las Vegas Strip Circuit", "Las Vegas", "USA"),
    ("Yas Marina Circuit", "Yas Island", "Abu Dhabi")
]
def forwards(apps, *args, **kwargs):
    Location = apps.get_model("events", "Location")

    for circuit_name, city, country in input:
        Location.objects.create(circuit_name=circuit_name, city=city, country=country)

def backwards(apps, *args, **kwargs):
    Location = apps.get_model("events", "Location")

    Location.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_grandprix'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
