# Generated by Django 4.2 on 2023-04-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    def forwards(apps, *args, **kwargs):
        GrandPrix = apps.get_model("events", "GrandPrix")
        Location = apps.get_model("events", 'Location')

        GrandPrix.objects.create(grand_prix_name="default")
        Location.objects.create(circuit_name="default", city="default", country="default")

    def backwards(apps, *args, **kwargs):
        GrandPrix = apps.get_model("events", "GrandPrix")
        Location = apps.get_model("events", 'Location')

        GrandPrix.objects.get(grand_prix_name="default").delete()
        Location.objects.get(circuit_name="default").delete()

    dependencies = [
        ('events', '0006_initial_data_grandprix'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
