# Generated by Django 4.2 on 2023-04-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_adding_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='grand_prix_name',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='events.grandprix'),
        ),
        migrations.AlterField(
            model_name='event',
            name='circuit_name',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, to='events.location'),
        ),
    ]
